Set version with SETUP SCM TOOLS properly.
conda-forge/fparser-feedstock pull request #16
Opened 2024-09-25 17:01 UTC by wolfv

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-09-25 21:19 UTC, wolfv commented
@conda-forge/fparser this fixes an issue where the installed version is detected as `0.0.0` which is problematic for later `pip check` checks :)

2024-09-30 13:50 UTC, MatthewHambley requested changes
The purpose of this change is to handle the problem that the library is not being built from a VCS working copy but expects to derive a version number from one. This all seems to be in order.

However there are also a lot of other changes to Conda-forge automatically generated and maintained files unrelated to this goal. Please back these out leaving only the headline change.

If there are improvements to be had to the way we interact with the Conda-forge infrastructure please raise them as a separate pull request.

2024-09-30 14:54 UTC, wolfv commented
Hi @MatthewHambley thank you for reviewing. These changes are indeed made automatically by `conda-smithy`, for example to update the README or build scripts for Azure. This should almost always be done when submitting a PR, but we can also ask the bot to rerender just to be sure.

@conda-forge-admin, please rerender

2024-09-30 14:54 UTC, wolfv commented
In #17 I was asked to remove rupert from the list of maintainers, which I now also did in this PR.

2024-10-21 13:19 UTC, konradha commented
Hi, any updates on this? @MatthewHambley

2025-01-20 10:41 UTC, MatthewHambley approved these changes
Since it seems we have to take Forge's changes at the same time I think it's best to go ahead with this change as it is.

2025-01-20 10:54 UTC, MatthewHambley commented
Attempted to resolve conflicts but don't know enough about how Forge works to understand resulting failures.

2025-02-11 16:01 UTC, MatthewHambley commented
@conda-forge-admin, please rerender

2025-02-11 16:10 UTC, merged